### ISSUE TITLE
Reviews not getting after review page

### ISSUE THREAD

**Issue by hparik11** [adamlwgriffiths/amazon_scraper#20]
I am getting the reviews for first review page. But after first page how would I get the reviews for other pages?

**Comment by adamlwgriffiths** [comment]
What is the code you are using? I can't help unless you give me more information.

I've updated some of the documentation, if it is insufficient you can always look at the code for the `Reviews` class, it's easy to understand.

https://github.com/adamlwgriffiths/amazon_scraper/blob/master/amazon_scraper/reviews.py

**Comment by hparik11** [comment]
![issue](https://cloud.githubusercontent.com/assets/13894488/11481732/bdc59a40-9764-11e5-8d48-0d2bccef9973.png)

**Comment by adamlwgriffiths** [comment]
Thanks, I've fixed it in 90df4439f345843e5bb2005bc9f3ce2144517acb. Pushed a new release, 0.3.2.
Yet another differently styled amazon tag.

Please confirm it's fixed for you.

**Comment by hparik11** [comment]
Hey,

Still I'm not getting the reviews of another page. I am still getting 10 reviews only.

**Comment by adamlwgriffiths** [comment]
Tests are passing
Verified that there are more than 10 brief and full reviews.

Are you sure you've upgraded to 0.3.2?
`pip install --upgrade amazon_scraper==0.3.2`
